### ISSUE TITLE
not too bad

### ISSUE THREAD

**Issue by DvonHolten** [arminbiere/kissat#1]
compilation on cygwin64 worked smooth - the test-thing aborted with a message 'fatal error  file /etc/passwd determined to be writable unexpectedly' - why the heck does it want to write my passwd file ? never mind.
execution ( on cygwin64 ) is fine. Some early results compared to cadical october 2019:
seconds, incl reading
```
kissat     cadcal
   86         216
  370         390
   60          89
   58         131
  207         820
```

gar nicht mal so schlecht - weiter so!

**Comment by arminbiere** [comment]
Thanks, for checking. This file reading and writing (compressed too) has been a source of hard to test and debug problems in the past.  That is why there are low-level unit tests for this.  Here the 'kissat_file_writable' function is tested, which should return 'false' for '/etc/passwd' (otherwise something is seriously is wrong on your system). Strange that this failed on your system.  Can you try (as ordinary user): touch /etc/passwd?

**Comment by deiruch** [comment]
Cygwin is Windows, and /etc/passwd has no special meaning there. Quoting the Cygwin documentation:

> Cygwin doesn't need this file, because it reads user information from the Windows account databases

In my tests, this file doesn't even exist on a default Cygwin installation. Cygwin treats /etc/passwd like any other non-existing file.

**Comment by arminbiere** [comment]
I have in the mean time tested Kissat on Cygwin (also fixed two other gcc-9.x issue this way because gcc 9 is default on Cygwin).  These fixes will go into a future release.

**Comment by arminbiere** [comment]
Fixed in sc2021 release.
