### ISSUE TITLE
Proofs?

### ISSUE THREAD

**Issue by DennisYurichev** [arminbiere/kissat#23]
How to generate proofs?
I tried (latest) kissat -f fname.cnf, but no file created...

**Comment by krobelus** [comment]
On Mon, Jan 31, 2022 at 07:53:35PM -0800, DennisYurichev wrote:
> How to generate proofs?
> I tried (latest) kissat -f fname.cnf, but no file created...

check the synopsis, you need to pass the path to the proof as second argument.

	kissat <(printf 'p cnf 1 2\n1 0\n-1 0') proof.drat

By default, kissat will refuse to write proofs to existing *.cnf files,
because that's likely a user error. Flag -f means "write it anyway".

**Comment by DennisYurichev** [comment]
Sorry, couldn't understand.
I can run this with success:
    cat myfile.cnf | kissat
But not:
    cat myfile.cnf | kissat proof.drat
Neither:
    cat myfile.cnf | kissat -f proof.drat

**Comment by krobelus** [comment]
If I run "kissat -h" the synopsis line is

	usage: kissat [ <option> ... ] [ <dimacs> [ <proof> ] ]

so if `<proof>` is given, then `<dimacs>` must be given as well, to prevent
any ambiguity. Hence, valid invocations are

	kissat			# (read formula from stdin)
	kissat myfile.cnf
	kissat myfile.cnf proof.drat

Passing by filename can be better than stdin, since it allows on-the-fly
decompression (see "build/kissat --help | less +/Furthermore").  This is
also the standard format used in competitions.

If you really want to read from stdin and write a proof you can use

	cat myfile.cnf | kissat /dev/stdin proof.drat

(/dev/stdin is available at least on Linux)

```diff
diff --git a/src/application.c b/src/application.c
index 57b1075..453ab9e 100644
--- a/src/application.c
+++ b/src/application.c
@@ -107,3 +107,3 @@ print_force_usage (void)
 #if !defined(NPROOFS) && defined(_POSIX_C_SOURCE)
-  printf ("  -f      force writing proofs (to existing CNF alike file)\n");
+  printf ("  -f      overwrite proof even if it looks like a CNF file\n");
 #elif !defined(NPROOFS) && !defined(_POSIX_C_SOURCE)
```

**Comment by DennisYurichev** [comment]
Thanks for your answer!
