### ISSUE TITLE
is kissat non-deterministic?

### ISSUE THREAD

**Issue by jwaldmann** [arminbiere/kissat#49]
The following may sound a bit strange, but ...

I think kissat (3.1.1) found a model for a CNF (roughly 200k vars, 1m clauses), using  `--sat --quiet 1`, after perhaps 15 min,  but I am unable to reproduce it, in several tries, giving more than 1 hour each. So - was I hallucinating? Or was kissat just lucky? 

The `--help` text includes
```
  --sat      target satisfiable instances ('--target=2 --restartint=50')
  --target=0..2              target phases (1=stable,2=focused) [1]
  --randec=<bool>            random decisions [true]
  --randecstable=<bool>      random decisions in stable mode [false]
  --randecfocused=<bool>     random decisions in focused mode [true]
```
meaing that it _was_ random?

Assuming yes: what's the best strategy to find a model (again)? Just run repeatedly, with timeout? Or run once, without timeout? (of course I will try both.)

**Comment by arminbiere** [comment]
It should be deterministic across machines, operating systems and configurations.  Well there is one issue if the file has options in it and you have compiled with `--embedded` which is default for debugging  (`-g`) and some other configurations.  In the default configuration these options in DIMACS files are ignored though and then you get strange Heisenbugs for the debugging configuration.  Otherwise this could be also a hardware glitch.

**Comment by arminbiere** [comment]
```
$ kissat --help|grep seed
  --seed=0...                random seed [0]

```

**Comment by arminbiere** [comment]
Probably I should also add a `--thanks=<string-hashed-to-seed>`, e.g., `--thanks=bad\ mood` which then as in Vampire prints at the end
```
s UNSATISFIABLE
c thanks to bad mood
```

**Comment by arminbiere** [comment]
Good, then I close this.
