### ISSUE TITLE
kissat 4.0.0 doesn't compile with `--compact` flag

### ISSUE THREAD

**Issue by firefighterduck** [arminbiere/kissat#54]
The new version 4.0.0 that was submitted to this years SAT competition (btw. congratulations on the amazing win) does not compile if the `--compact` flag is enabled (also if `--extreme` or `--ultimate` are enabled). To be more precise the new [factor.c](https://github.com/arminbiere/kissat/blob/faa674e324b76c3348b34f40beaa0b9d821b84c2/src/factor.c) file contains two occurrences where the `SIZE_STACK` macro is used on watches, which does not work in the case of the compact representation.

https://github.com/arminbiere/kissat/blob/faa674e324b76c3348b34f40beaa0b9d821b84c2/src/factor.c#L273
https://github.com/arminbiere/kissat/blob/faa674e324b76c3348b34f40beaa0b9d821b84c2/src/factor.c#L562

**Comment by arminbiere** [comment]
Thanks for spotting this. I have not been using '--compact' much lately since it seems to limit the capacity of the solver too much.  This is a non-default configuration parameter anyhow used to reduce memory usage a bit, even though Kissat is anyhow much more compact than other solvers (2-4 more compact than CaDiCaL for instance).  I will check whether this feature is necessary still.

**Comment by arminbiere** [comment]
BTW, for this year' competition the '--competition' configuration forces only '--no-options' and '--quiet'.

**Comment by firefighterduck** [comment]
Tbh I don't know whether the `--compact` flag makes any difference/sense for my use case of kissat, I just used the `--ultimate` flag, since it sounds like the best option out-of-the-box.

**Comment by arminbiere** [comment]
Fixed in release 4.0.1.
